<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="../Realm.Domain/Realm.Domain.csproj" />
    <ProjectReference Include="../Realm.Infrastructure/Realm.Infrastructure.csproj" />
    <ProjectReference Include="../Realm.Demo/Realm.Demo.csproj" />
  </ItemGroup>

</Project>
